### ISSUE TITLE
[Feature]: Ice Floor Theo Toggle

### ISSUE THREAD

**Issue by btd4player** [CommunalHelper/CavernHelper#2]
### Request Description

A toggle that let's theo slide along ice floors just as crystal bombs do. It's for a collab map i'm making, where it being theo is important.

**Comment by bigkahuna443** [comment]
The icy floor entity is really just a graphical entity, all the sliding logic is specific to the crystal bomb. Adding new holdables would require some complicated logic to be patched into Theo/jellies/etc. This might make more sense as a request to [Vortex Helper](https://github.com/CommunalHelper/VortexHelper) since they already have a Floor Booster entity that has player friction?
